#pragma once

#include "attach_shader.hpp"
#include "compile_shader.hpp"
#include "create_program.hpp"
#include "create_shader.hpp"
#include "delete_program.hpp"
#include "delete_shader.hpp"
#include "get_active_attrib.hpp"
#include "get_program.hpp"
#include "get_uniform_location.hpp"
#include "link_program.hpp"
#include "program_uniform_matrix.hpp"
#include "program_uniform_v.hpp"
#include "program_uniform.hpp"
#include "shader_source.hpp"
#include "use_program.hpp"
